# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ArticleContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, content=None):  # noqa: E501
        """ArticleContent - a model defined in OpenAPI

        :param name: The name of this ArticleContent.  # noqa: E501
        :type name: str
        :param content: The content of this ArticleContent.  # noqa: E501
        :type content: str
        """
        self.openapi_types = {
            'name': str,
            'content': str
        }

        self.attribute_map = {
            'name': 'name',
            'content': 'content'
        }

        self._name = name
        self._content = content

    @classmethod
    def from_dict(cls, dikt) -> 'ArticleContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ArticleContent of this ArticleContent.  # noqa: E501
        :rtype: ArticleContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this ArticleContent.


        :return: The name of this ArticleContent.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ArticleContent.


        :param name: The name of this ArticleContent.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def content(self):
        """Gets the content of this ArticleContent.


        :return: The content of this ArticleContent.
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this ArticleContent.


        :param content: The content of this ArticleContent.
        :type content: str
        """
        if content is None:
            raise ValueError("Invalid value for `content`, must not be `None`")  # noqa: E501

        self._content = content
