# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Category(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, category_id=None, name=None):  # noqa: E501
        """Category - a model defined in OpenAPI

        :param category_id: The category_id of this Category.  # noqa: E501
        :type category_id: int
        :param name: The name of this Category.  # noqa: E501
        :type name: str
        """
        self.openapi_types = {
            'category_id': int,
            'name': str
        }

        self.attribute_map = {
            'category_id': 'category_id',
            'name': 'name'
        }

        self._category_id = category_id
        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> 'Category':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Category of this Category.  # noqa: E501
        :rtype: Category
        """
        return util.deserialize_model(dikt, cls)

    @property
    def category_id(self):
        """Gets the category_id of this Category.

        ID 编号  # noqa: E501

        :return: The category_id of this Category.
        :rtype: int
        """
        return self._category_id

    @category_id.setter
    def category_id(self, category_id):
        """Sets the category_id of this Category.

        ID 编号  # noqa: E501

        :param category_id: The category_id of this Category.
        :type category_id: int
        """
        if category_id is None:
            raise ValueError("Invalid value for `category_id`, must not be `None`")  # noqa: E501

        self._category_id = category_id

    @property
    def name(self):
        """Gets the name of this Category.

        名称  # noqa: E501

        :return: The name of this Category.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Category.

        名称  # noqa: E501

        :param name: The name of this Category.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name
